# Generated by Django 5.0.4 on 2024-05-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='govprice',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='opencost',
        ),
        migrations.AddField(
            model_name='govprice',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='govprice_crops', to='shs.crop', verbose_name='Govt. Price'),
        ),
        migrations.AddField(
            model_name='openprice',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opencost_crops', to='shs.crop', verbose_name='Open Market Price'),
        ),
    ]
