# Generated by Django 5.0.4 on 2024-05-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shs', '0002_remove_crop_govprice_remove_crop_opencost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='Biopesticide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biopesticide_crops', to='shs.biopesticide', verbose_name='Biopesticide'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fertilizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_crops', to='shs.fertilizer', verbose_name='Fertilizer'),
        ),
        migrations.AlterField(
            model_name='govprice',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='govprice_crops', to='shs.crop', verbose_name='Crop name'),
        ),
        migrations.AlterField(
            model_name='openprice',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opencost_crops', to='shs.crop', verbose_name='Crop'),
        ),
    ]
