# Generated by Django 5.0.4 on 2024-05-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shs', '0003_alter_crop_biopesticide_alter_crop_fertilizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='Biopesticide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biopesticide_crops', to='shs.biopesticide', verbose_name='Biopesticide'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fertilizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_crops', to='shs.fertilizer', verbose_name='Fertilizer'),
        ),
    ]
