# Generated by Django 5.0.4 on 2024-05-04 19:23

import User_prof.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(default='User', max_length=20, null=True, verbose_name='first name')),
                ('last_name', models.CharField(default=' ', max_length=20, null=True, verbose_name='last name')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('prof_image', models.ImageField(default='static/images/user.png', max_length=1000, upload_to=User_prof.models.set_profile_image)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='profile_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='profile_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_prof.profile')),
            ],
        ),
    ]
